### ISSUE TITLE
create BOM

### ISSUE THREAD

**Issue by moedn** [moedn/MagnetTestStation#1]
the README currently says:

```
## Required Material

- Arduino board
- A1324LUA-T Hall sensor
- 3D Printer for printing the frame
- Python 3 with the following libraries installed:
    - PyQt6
    - numpy
    - pyserial
```

I'd separate this into 2…3 lists:

1. all physical components involved
2. all software dependencies
3. (optional) tools needed

---

### ToDo/Clarifications

- [x] which Arduino Board has been used?
- [x] any other components except for the Arduino board, the hall sensor and the 3 spacer parts + frame? any cables for instance?

**Comment by umbertozanovello** [comment]
I used the Arduino UNO board but every board should be suitable as long as it is provided with a USB connector to interface to the PC. Otherwise you would need an external USB to serial UART interface which makes things a little bit more complicated.
Yes, of course you need three signal cables and the cable to connect to the PC; good point!

Here are the lists:

1 Required physical components:
    - Arduino board (any Arduino board provided with a USB interface, one Vcc and GND pin and one Analog input pin)
    - One USB cable for connecting the Arduino board to the local PC
    - Three jumper cable to supply the Hall sensor and read the measured signal
    - A1324LUA-T Hall sensor
    - 3D Printer for printing the frame
    - A PC with Windows or Linux OS

2 Software dependencies:
    - Python 3 with the following libraries installed:
        - PyQt6
        - numpy
        - pyserial

 3 (optional) tools needed:
    - Still nothing here I think.

Many thanks!!

**Comment by moedn** [comment]
done, thanks!
